config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :quizzes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "quizzes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  skip_before_action :verify_authenticity_token
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy!

    respond_to do |format|
      format.html { redirect_to questions_path, status: :see_other, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.expect(question: [ :name, :quiz_id ])
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: "Quiz was successfully created." }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy!

    respond_to do |format|
      format.html { redirect_to quizzes_path, status: :see_other, notice: "Quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.expect(quiz: [ :title, :description ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Einars App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :quiz_id, style: "display: block" %>
    <%= form.text_field :quiz_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <p>
    <strong>Name:</strong>
    <%= question.name %>
  </p>

  <p>
    <strong>Quiz:</strong>
    <%= question.quiz_id %>
  </p>

</div>

app/views/questions/edit.html.erb
<% content_for :title, "Editing question" %>

<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Questions" %>

<h1>Questions</h1>

<div id="questions">
  <% @questions.each do |question| %>
    <%= render question %>
    <p>
      <%= link_to "Show this question", question %>
    </p>
  <% end %>
</div>

<%= link_to "New question", new_question_path %>
<div>
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/questions/new.html.erb
<% content_for :title, "New question" %>

<h1>New question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz) do |form| %>
  <% if quiz.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
        <% quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>">
  <p>
    <strong>Title:</strong>
    <%= quiz.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= quiz.description %>
  </p>

</div>

app/views/quizzes/edit.html.erb
<% content_for :title, "Editing quiz" %>

<h1>Editing quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Show this quiz", @quiz %> |
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Quizzes" %>

<h1>Quizzes</h1>

<div id="quizzes">
  <% @quizzes.each do |quiz| %>
    <%= render quiz %>
    <p>
      <%= link_to "Show this quiz", quiz %>
    </p>
  <% end %>
</div>

<%= link_to "New quiz", new_quiz_path %>
<div>
  <%= link_to "Questions", questions_path %>
</div>

app/views/quizzes/new.html.erb
<% content_for :title, "New quiz" %>

<h1>New quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quiz %>

<div>
  <%= link_to "Edit this quiz", edit_quiz_path(@quiz) %> |
  <%= link_to "Back to quizzes", quizzes_path %>

  <%= button_to "Destroy this quiz", @quiz, method: :delete %>
</div>